SQLの提出
yanagiseira71717/sample_repository pull request #11
Opened 2024-06-08 12:04 UTC by yanagiseira71717

SQL基礎　for PHP
以上となります。
お手すきの際にご確認のほどよろしくお願いいたします。

2024-06-10 01:43 UTC, cin-sakino requested changes
お手隙でご確認お願いいたします！

2024-06-10 01:43 UTC, cin-sakino commented on SQL基礎 for PHP/sql_basic.sql
> +            join
ここは割合がマックスのやつだけ取得したいと思うので`INNSER JOIN`にしておきましょう！

2024-06-10 01:43 UTC, cin-sakino commented on SQL基礎 for PHP/sql_basic.sql
> +	ON  countries.code = countrylanguages.country_code
ついでにインデントも揃えておきましょう！

2024-06-10 12:54 UTC, yanagiseira71717 commented on SQL基礎 for PHP/sql_basic.sql
> +            join
お疲れ様です。ご確認いただきましてありがとうございます。
こちら修正いたしましたので再度確認していただけますと幸いです。

何卒宜しくお願い致します。

2024-06-12 01:52 UTC, cin-sakino approved these changes
[この指摘](https://github.com/yanagiseira71717/sample_repository/pull/11#discussion_r1632487381)も対応していただきたかったですが、致命的なものではないのでOKとします！
今後は指摘に対して修正漏れがないように意識するようにしましょう！💪

2024-06-12 07:46 UTC, yanagiseira71717 commented on SQL基礎 for PHP/sql_basic.sql
> +	ON  countries.code = countrylanguages.country_code
大変失礼いたしました。
今後はこのようなことがないように気をつけます。

何卒宜しくお願い致します。

2024-06-12 07:47 UTC, merged